[versions]
androidSdk = "36"
androidMinSdk = "29"

androidsvgAar = "1.4"
androidxActivity = "1.13.0-alpha01" # https://developer.android.com/jetpack/androidx/releases/activity
atomicfu = "0.29.0"  # https://github.com/Kotlin/kotlinx-atomicfu/releases
barcodeScanning = "17.3.0"
bigNumVersion = "0.3.10" # https://github.com/ionspin/kotlin-multiplatform-bignum

bu_libnexakotlin = "0.5.26" # https://gitlab.com/nexa/libnexakotlin
bu_mpthreads = "0.5.6" # https://gitlab.com/nexa/mpthreads
bu_nexaRpc = "1.6.3" # https://gitlab.com/nexa/nexarpckotlin

cameraCamera2 = "1.5.2" # https://developer.android.com/jetpack/androidx/releases/camera
coreKtx = "1.7.0" # https://mvnrepository.com/artifact/androidx.test/core
coroutinesVersion = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines
jsvg = "2.0.0"
junitKtx = "1.3.0"
kotlinxDatetime = "0.7.1"
ksoup = "0.2.5"
lifecycleViewmodelCompose = "2.9.6"
lottieVersion = "6.7.1"
ktorVersion = "3.3.3" # https://github.com/ktorio/ktor
material = "1.13.0"
materialIconsExtended = "1.7.8"
media3Exoplayer = "1.9.0"
nativeDriver = "2.2.1"
kotlin = "2.3.10" # https://github.com/JetBrains/kotlin/releases
compose = "1.10.0" # https://github.com/JetBrains/compose-multiplatform/releases
composeAndroid = "1.10.1" # The Android-only version of compose. This version occasionally deviates from the multiplatform version of compose.
composeJunitAndroid = "1.10.1"
mat3 = "1.9.0"
android-gradle-plugin = "8.13.2" # Tied to IDE version so do not just bump forward. https://developer.android.com/build/releases/gradle-plugin
kover = "0.9.4"
okio = "3.16.4"
playServicesBase = "18.10.0"
qrose = "1.0.1"
serializationVersion = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization
task-tree = "4.0.1"
skiko = "0.9.37.3" # https://github.com/JetBrains/skiko/releases  (needs to be aligned with compose skiko dependency for JVM to work)
tracing = "1.3.0"
uriKmpVersion = "0.0.21" # https://github.com/eygraber/uri-kmp
wear = "1.3.0"
workVersion = "2.11.0" # https://developer.android.com/jetpack/androidx/releases/work
zxingAndroidEmbedded = "4.3.0"

[libraries]
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvgAar" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCamera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeAndroid" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "composeAndroid" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "tracing" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeAndroid" }
androidx-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "composeJunitAndroid" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeAndroid" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workVersion" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bigNumVersion" }
bignum-serialization-kotlinx = { module = "com.ionspin.kotlin:bignum-serialization-kotlinx", version.ref = "bigNumVersion" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "mat3" }
jsvg = { module = "com.github.weisj:jsvg", version.ref = "jsvg" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutinesVersion" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serializationVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationVersion" }
kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "serializationVersion" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorVersion" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorVersion" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorVersion" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "nativeDriver" }
nexa-mpthreads = { module = "org.nexa:mpthreads", version.ref = "bu_mpthreads" }
nexa-rpc = { module = "org.nexa:nexarpc", version.ref = "bu_nexaRpc" }
nexa-libnexakotlin = { module = "org.nexa:libnexakotlin", version.ref = "bu_libnexakotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeAndroid" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uriKmpVersion" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
ui-tooling-preview = { module =  "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose"  }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }
compose = { id = "org.jetbrains.compose", version.ref = "compose"}